[tool.ruff]
line-length = 120
lint.select = ["E", "F"]
lint.ignore = ["E501"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = false
warn_return_any = false
no_implicit_optional = false
